-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "jenis_mesin" (
	"id" serial PRIMARY KEY NOT NULL,
	"nama" varchar(255) NOT NULL,
	"kode_mesin" text,
	"status" integer,
	CONSTRAINT "data_mesin_nama_key" UNIQUE("nama")
);
--> statement-breakpoint
CREATE TABLE "kaos_kaki" (
	"id" serial PRIMARY KEY NOT NULL,
	"nama" varchar(255) NOT NULL,
	"jenis_bahan_id" integer,
	"keterangan" text,
	"last_order_date" date,
	"createdAt" timestamp with time zone,
	"updatedAt" timestamp with time zone,
	"kode_kaos_kaki" text,
	"status" integer,
	CONSTRAINT "uk_nama_jenis" UNIQUE("nama","jenis_bahan_id")
);
--> statement-breakpoint
CREATE TABLE "jenis_bahan" (
	"id" serial PRIMARY KEY NOT NULL,
	"nama" varchar(255) NOT NULL,
	"kode_bahan" text,
	"status" integer,
	CONSTRAINT "jenis_bahan_nama_key" UNIQUE("nama")
);
--> statement-breakpoint
CREATE TABLE "ukuran" (
	"id" serial PRIMARY KEY NOT NULL,
	"nama" varchar(255) NOT NULL,
	"kode_ukuran" text,
	"status" integer,
	CONSTRAINT "ukuran_nama_key" UNIQUE("nama")
);
--> statement-breakpoint
CREATE TABLE "warna" (
	"id" serial PRIMARY KEY NOT NULL,
	"nama" varchar(255) NOT NULL,
	"kode_warna" text,
	"status" integer,
	CONSTRAINT "warna_nama_key" UNIQUE("nama")
);
--> statement-breakpoint
CREATE TABLE "pesanan" (
	"id" serial PRIMARY KEY NOT NULL,
	"nama_pemesan" varchar(255) NOT NULL,
	"catatan" text,
	"createdAt" timestamp with time zone DEFAULT now(),
	"status" integer,
	"updatedAt" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "pesanan_detail" (
	"id" serial PRIMARY KEY NOT NULL,
	"pesanan_id" integer NOT NULL,
	"kaos_kaki_variasi_id" integer NOT NULL,
	"jumlah" integer NOT NULL,
	"harga_satuan" numeric(10, 2) NOT NULL,
	CONSTRAINT "pesanan_detail_harga_satuan_check" CHECK (harga_satuan > (0)::numeric),
	CONSTRAINT "pesanan_detail_jumlah_check" CHECK (jumlah > 0)
);
--> statement-breakpoint
CREATE TABLE "foto_kaos_kaki" (
	"id" serial PRIMARY KEY NOT NULL,
	"kaos_kaki_id" integer NOT NULL,
	"url" text NOT NULL,
	"is_primary" boolean DEFAULT false,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "data_mesin" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "data_mesin_id_seq1" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"kaos_kaki_id" integer,
	"jenis_mesin_id" integer,
	"updatedAt" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "data_mesin" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "status" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"enum" integer,
	"message" text,
	"cratedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "status" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nama_user" varchar,
	"email" varchar,
	"password" varchar,
	"refresh_token" varchar DEFAULT 'refresh_token_secret_key' NOT NULL,
	"telephone_number" varchar,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "stok_kaos_kaki" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stok_kaos_kaki_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id_kaos" integer,
	"id_ukuran" integer,
	"id_warna" integer,
	"stok" bigint,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "stok_kaos_kaki" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "kaos_kaki_variasi_detail" (
	"id" serial PRIMARY KEY NOT NULL,
	"kaos_kaki_id" integer NOT NULL,
	"ukuran_id" integer NOT NULL,
	"warna_id" integer NOT NULL,
	CONSTRAINT "uk_variasi" UNIQUE("kaos_kaki_id","ukuran_id","warna_id")
);
--> statement-breakpoint
ALTER TABLE "kaos_kaki" ADD CONSTRAINT "kaos_kaki_jenis_bahan_id_fkey" FOREIGN KEY ("jenis_bahan_id") REFERENCES "public"."jenis_bahan"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pesanan_detail" ADD CONSTRAINT "pesanan_detail_kaos_kaki_variasi_id_fkey" FOREIGN KEY ("kaos_kaki_variasi_id") REFERENCES "public"."kaos_kaki_variasi_detail"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pesanan_detail" ADD CONSTRAINT "pesanan_detail_pesanan_id_fkey" FOREIGN KEY ("pesanan_id") REFERENCES "public"."pesanan"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "foto_kaos_kaki" ADD CONSTRAINT "foto_kaos_kaki_kaos_kaki_id_fkey" FOREIGN KEY ("kaos_kaki_id") REFERENCES "public"."kaos_kaki"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "data_mesin" ADD CONSTRAINT "data_mesin_jenis_mesin_id_fkey" FOREIGN KEY ("jenis_mesin_id") REFERENCES "public"."jenis_mesin"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "data_mesin" ADD CONSTRAINT "data_mesin_kaos_kaki_id_fkey" FOREIGN KEY ("kaos_kaki_id") REFERENCES "public"."kaos_kaki"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stok_kaos_kaki" ADD CONSTRAINT "stok_kaos_kaki_id_kaos_fkey" FOREIGN KEY ("id_kaos") REFERENCES "public"."kaos_kaki"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stok_kaos_kaki" ADD CONSTRAINT "stok_kaos_kaki_id_ukuran_fkey" FOREIGN KEY ("id_ukuran") REFERENCES "public"."ukuran"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stok_kaos_kaki" ADD CONSTRAINT "stok_kaos_kaki_id_warna_fkey" FOREIGN KEY ("id_warna") REFERENCES "public"."warna"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kaos_kaki_variasi_detail" ADD CONSTRAINT "kaos_kaki_variasi_kaos_kaki_id_fkey" FOREIGN KEY ("kaos_kaki_id") REFERENCES "public"."kaos_kaki"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kaos_kaki_variasi_detail" ADD CONSTRAINT "kaos_kaki_variasi_ukuran_id_fkey" FOREIGN KEY ("ukuran_id") REFERENCES "public"."ukuran"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kaos_kaki_variasi_detail" ADD CONSTRAINT "kaos_kaki_variasi_warna_id_fkey" FOREIGN KEY ("warna_id") REFERENCES "public"."warna"("id") ON DELETE no action ON UPDATE no action;
*/